# Generated by Django 5.2.17 on 2026-09-24 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Được duyệt'), ('rejected', 'Bị từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_starts_at', models.DateTimeField()),
                ('registered_ends_at', models.DateTimeField()),
                ('registered_address', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='activities.activity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_participations', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at', '-id'],
                'indexes': [models.Index(fields=['activity', 'status'], name='participati_activit_818e56_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'volunteer'), name='participation_unique_volunteer'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'cancelled'])), name='participation_valid_status')],
            },
        ),
    ]
