# Generated by Django 5.2.17 on 2026-09-25 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_attendances', to=settings.AUTH_USER_MODEL)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='participations.participation')),
            ],
            options={
                'ordering': ['-confirmed_at', '-id'],
            },
        ),
    ]
