# Generated by Django 5.2.17 on 2026-10-04 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_cover_activity_required_skills'),
        ('participations', '0002_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('manual', 'Thủ công'), ('qr', 'Quét QR'), ('code', 'Nhập mã')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nonce', models.UUIDField(default=uuid.uuid4)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_code', to='activities.activity')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
