# Generated by Django 5.2.17 on 2026-10-08 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_attendance_method_attendancecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contribution', to='participations.attendance')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ContributionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('previous_minutes', models.PositiveIntegerField(null=True)),
                ('minutes', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='participations.contribution')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('contribution', 'revision'), name='contribution_unique_revision')],
            },
        ),
    ]
