# Generated by Django 5.2.17 on 2026-10-04 05:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_activity_cover_activity_required_skills'),
        ('participations', '0002_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('href', models.CharField(max_length=300)),
                ('dedupe_key', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=40)),
                ('reminder_starts_at', models.DateTimeField(null=True)),
                ('reminder_reviewed_at', models.DateTimeField(null=True)),
                ('reminder_participation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participations.participation')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='notificatio_recipie_da81fd_idx'),
        ),
    ]
