# Generated by Django 5.2.17 on 2026-09-25 14:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participations', '0002_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=1000)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='participations.attendance')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hidden_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_range'), models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='feedback_content_not_empty'), models.CheckConstraint(condition=models.Q(models.Q(('hidden_at__isnull', True), ('hidden_by__isnull', True), ('hidden_reason', ''), ('is_hidden', False)), models.Q(('hidden_at__isnull', False), ('hidden_by__isnull', False), ('is_hidden', True), models.Q(('hidden_reason', ''), _negated=True)), _connector='OR'), name='feedback_hidden_audit_required')],
            },
        ),
    ]
