# Generated by Django 5.2.17 on 2026-09-15 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Giới thiệu'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Số điện thoại'),
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='Tên tổ chức')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='Mô tả tổ chức')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='Website')),
                ('contact_address', models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ liên hệ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
