# Generated by Django 5.2.17 on 2026-09-16 04:23

import django.core.validators
from django.db import migrations, models


def assign_existing_admin_usernames(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.using(schema_editor.connection.alias).filter(role='admin').iterator():
        user.username = 'admin_' + user.pk.hex
        user.save(using=schema_editor.connection.alias, update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.-]+$', 'Username chỉ gồm chữ không dấu, số, dấu chấm, gạch dưới hoặc gạch ngang.')], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.RunPython(assign_existing_admin_usernames, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'admin'), ('username__isnull', False), models.Q(('username', ''), _negated=True)), models.Q(('email__isnull', False), ('role__in', ['volunteer', 'organizer']), ('username__isnull', True), models.Q(('email', ''), _negated=True)), _connector='OR'), name='accounts_user_login_identity'),
        ),
    ]
