# Generated by Django 5.2.17 on 2026-09-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_phone_organizerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
