# Generated by Django 5.2.17 on 2026-09-27 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_session_version'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='Sở thích')),
                ('skills', models.ManyToManyField(blank=True, related_name='volunteer_profiles', to='core.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='Ngày trong tuần')),
                ('starts_at', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('ends_at', models.TimeField(verbose_name='Giờ kết thúc')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.volunteerprofile')),
            ],
            options={
                'ordering': ['weekday', 'starts_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='accounts_availability_weekday'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='accounts_availability_time_order'), models.UniqueConstraint(fields=('profile', 'weekday', 'starts_at', 'ends_at'), name='accounts_availability_unique_slot')],
            },
        ),
    ]
