# Generated by Django 5.2.17 on 2026-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_volunteerprofile_availabilityslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='matching_visible',
            field=models.BooleanField(default=False, verbose_name='Cho phép xuất hiện trong gợi ý'),
        ),
    ]
