# Generated by Django 5.2.17 on 2026-09-22 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Tên hoạt động')),
                ('description', models.TextField(max_length=10000, verbose_name='Mô tả')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('starts_at', models.DateTimeField(verbose_name='Bắt đầu')),
                ('ends_at', models.DateTimeField(verbose_name='Kết thúc')),
                ('capacity', models.PositiveIntegerField(verbose_name='Sức chứa')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Công khai'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organizer', 'status'], name='activities__organiz_ab2ad8_idx'), models.Index(fields=['status', 'starts_at'], name='activities__status_d9464f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='activity_valid_dates'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity__lte', 100000)), name='activity_valid_capacity'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'completed', 'cancelled'])), name='activity_valid_status')],
            },
        ),
    ]
