# Generated by Django 5.2.17 on 2026-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cover',
            field=models.ImageField(blank=True, upload_to='activities/covers/', verbose_name='Ảnh bìa'),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='activities', to='core.skill'),
        ),
    ]
