# Generated by Django 5.2.17 on 2026-10-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_cover_activity_required_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='activities.activity')),
            ],
            options={
                'ordering': ['starts_at', 'ends_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='milestone_valid_dates')],
            },
        ),
    ]
