# Generated by Django 5.2.17 on 2026-09-26 02:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('account_locked', 'Khóa tài khoản'), ('account_unlocked', 'Mở khóa tài khoản'), ('review_approved', 'Duyệt đăng ký'), ('review_rejected', 'Từ chối đăng ký'), ('attendance_confirmed', 'Xác nhận có mặt'), ('feedback_hidden', 'Ẩn phản hồi')], max_length=40)),
                ('object_id', models.UUIDField()),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='activities.activity')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='reports_aud_action_fa4fdd_idx')],
            },
        ),
    ]
