# Generated by Django 5.2.17 on 2026-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('account_locked', 'Khóa tài khoản'), ('account_unlocked', 'Mở khóa tài khoản'), ('review_approved', 'Duyệt đăng ký'), ('review_rejected', 'Từ chối đăng ký'), ('attendance_confirmed', 'Xác nhận có mặt'), ('feedback_hidden', 'Ẩn phản hồi'), ('attendance_code_issued', 'Tạo mã điểm danh'), ('attendance_code_revoked', 'Thu hồi mã điểm danh')], max_length=40),
        ),
    ]
