# Generated by Django 5.2.17 on 2026-10-10 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activitymilestone'),
        ('reports', '0002_alter_auditevent_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='after',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='before',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('account_locked', 'Khóa tài khoản'), ('account_unlocked', 'Mở khóa tài khoản'), ('review_approved', 'Duyệt đăng ký'), ('review_rejected', 'Từ chối đăng ký'), ('attendance_confirmed', 'Xác nhận có mặt'), ('feedback_hidden', 'Ẩn phản hồi'), ('attendance_code_issued', 'Tạo mã điểm danh'), ('attendance_code_revoked', 'Thu hồi mã điểm danh'), ('activity_created', 'Tạo hoạt động'), ('activity_updated', 'Sửa hoạt động'), ('activity_status_changed', 'Đổi trạng thái hoạt động'), ('activity_cover_changed', 'Đổi ảnh bìa'), ('contribution_confirmed', 'Xác nhận đóng góp'), ('contribution_updated', 'Điều chỉnh đóng góp')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='reports_aud_actor_i_dda7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['subject', 'created_at'], name='reports_aud_subject_72c6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['activity', 'created_at'], name='reports_aud_activit_4ff524_idx'),
        ),
    ]
