# Generated by Django 5.2.17 on 2026-10-10 03:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0004_contribution_contributionchange'),
        ('reports', '0003_auditevent_after_auditevent_before_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('account_locked', 'Khóa tài khoản'), ('account_unlocked', 'Mở khóa tài khoản'), ('review_approved', 'Duyệt đăng ký'), ('review_rejected', 'Từ chối đăng ký'), ('attendance_confirmed', 'Xác nhận có mặt'), ('feedback_hidden', 'Ẩn phản hồi'), ('attendance_code_issued', 'Tạo mã điểm danh'), ('attendance_code_revoked', 'Thu hồi mã điểm danh'), ('activity_created', 'Tạo hoạt động'), ('activity_updated', 'Sửa hoạt động'), ('activity_status_changed', 'Đổi trạng thái hoạt động'), ('activity_cover_changed', 'Đổi ảnh bìa'), ('contribution_confirmed', 'Xác nhận đóng góp'), ('contribution_updated', 'Điều chỉnh đóng góp'), ('certificate_issued', 'Cấp chứng nhận'), ('certificate_revoked', 'Thu hồi chứng nhận')], max_length=40),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volunteer_name', models.CharField(max_length=255)),
                ('activity_title', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('minutes', models.PositiveIntegerField()),
                ('contribution_revision', models.PositiveIntegerField()),
                ('issued_by_name', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=1000)),
                ('active_attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_certificate', to='participations.attendance')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='participations.attendance')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('minutes__gt', 0)), name='certificate_positive_minutes'), models.CheckConstraint(condition=models.Q(models.Q(('active_attendance', models.F('attendance')), ('active_attendance__isnull', False), ('revocation_reason', ''), ('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('active_attendance__isnull', True), ('revoked_at__isnull', False), ('revoked_by__isnull', False), models.Q(('revocation_reason', ''), _negated=True)), _connector='OR'), name='certificate_valid_state')],
            },
        ),
    ]
